1. Create the Database and Table
CREATE DATABASE SOCIAL_MEDIA_FLOODGATES;

CREATE OR REPLACE TABLE SOCIAL_MEDIA_FLOODGATES.PUBLIC.TWEET_INGEST (
    RAW_STATUS VARIANT
);

2. Create JSON File Format
CREATE FILE FORMAT SOCIAL_MEDIA_FLOODGATES.PUBLIC.json_file_format
TYPE = 'JSON'
COMPRESSION = 'AUTO'
ENABLE_OCTAL = FALSE
ALLOW_DUPLICATE = FALSE
STRIP_OUTER_ARRAY = TRUE
STRIP_NULL_VALUES = FALSE
IGNORE_UTF8_ERRORS = FALSE;

3. Load JSON Data into Snowflake
COPY INTO SOCIAL_MEDIA_FLOODGATES.PUBLIC.TWEET_INGEST
FROM @UTIL_DB.PUBLIC.MY_INTERNAL_STAGE
FILES = ('nutrition_tweets.json')
FILE_FORMAT = (FORMAT_NAME = SOCIAL_MEDIA_FLOODGATES.PUBLIC.JSON_FILE_FORMAT);


Queries
1. Retrieve All Raw Data
SELECT RAW_STATUS
FROM TWEET_INGEST;

2. Extract Entities and Hashtags
SELECT RAW_STATUS:entities
FROM TWEET_INGEST;

SELECT RAW_STATUS:entities:hashtags
FROM TWEET_INGEST;

3. Retrieve First Hashtag Text
SELECT RAW_STATUS:entities:hashtags[0].text
FROM TWEET_INGEST
WHERE RAW_STATUS:entities:hashtags[0].text IS NOT NULL;

4. Convert Tweet Date
SELECT RAW_STATUS:created_at::date
FROM TWEET_INGEST
ORDER BY RAW_STATUS:created_at::date;

5. Flatten Nested Arrays (Extract URLs)
SELECT VALUE
FROM TWEET_INGEST,
LATERAL FLATTEN(INPUT => RAW_STATUS:entities:URLs);

6. Flatten Hashtags and Add Tweet Metadata
SELECT RAW_STATUS:user:name::text AS user_name,
       RAW_STATUS:id AS tweet_id,
       VALUE:text::varchar AS hashtag_used
FROM TWEET_INGEST,
LATERAL FLATTEN(INPUT => RAW_STATUS:entities:hashtags);
